name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'



env:
  LANG: "de_DE.UTF-8"
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: de_DE.UTF-8
      run: |
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8
    - name: Check out this repo
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: Fetch latest data
      run: |-
        sudo apt update
        sudo apt install libxml2-utils
        ./bin/run.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
